# Generated by Django 4.0 on 2022-07-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('located', models.CharField(max_length=100)),
                ('descriptions', models.TextField(blank=True, max_length=100)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(default=None)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='companies.company')),
            ],
        ),
    ]
